apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ombi
resources:
  - ombi-deploy.yml
  - ombi-svc.yml
  - ombi-ing.yml
  - ombi-pvc.yml
  - ombi-spc.yml
  - ombi-sa.yml
  - ombi-ns.yml
  - mariadb-deploy.yml
  - mariadb-svc.yml
  - mariadbexternal-deploy.yml
  - mariadbexternal-svc.yml
