kind: Deployment
apiVersion: apps/v1
metadata:
  name: mariadbexternal
  labels:
    app: mariadbexternal
    part-of: ombi
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadbexternal
      part-of: ombi
  template:
    metadata:
      labels:
        app: mariadbexternal
        part-of: ombi
    spec:
      serviceAccountName: ombi
      containers:
      - name: mariadbexternal
        image: ghcr.io/linuxserver/mariadb:latest
        ports:
        - name: mariadbexternal
          containerPort: 3306
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ombi
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_LOG_CONSOLE
          value: "true"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ombi
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: ombi
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ombi
              key: MYSQL_PASSWORD
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        volumeMounts:
        - name: ombi-secrets
          mountPath: "/mnt/vault"
          readOnly: true
      volumes:
      - name: ombi-secrets
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ombi"
